export enum routes {
  HOME_PAGE = '/',
  LOGIN_PAGE = 'login',
  POSTS_PAGE = 'posts',
  ADD_NOTICE_PAGE = 'add-notice',
  EDIT_NOTICE_PAGE = 'edit-notice',
  ADD_QUESTION_PAGE = 'add-question',
  EDIT_QUESTION_PAGE = 'edit-question',
  EDIT_PAYMENT_PAGE = 'edit-payment',
  USERS_PAGE = 'users',
  ADD_USER_PAGE = 'add-user',
  EDIT_USER_PAGE = 'edit-user',
  ADD_POST_PAGE = 'add-post',
  GET_POST = 'post',
  STORIES_PAGE = 'stories',
  ADD_STORY = 'add-story',
  EDIT_STORY = 'edit-story',
}
